### ISSUE TITLE
Help Needed: Memory Allocation Error in qeirreps.x

### ISSUE THREAD

**Issue by Amithigh** [qeirreps/qeirreps#6]
Hello everyone,

I created the input file using qe2respack and am encountering an error when trying to run the code for a 52 electrons primitive cell with SOC using following command /qeirreps-master/src/qeirreps.x directory/
I receive the following error message:reading: directory/
ncomp= 2

Operating system error: Cannot allocate memory
Allocation would exceed memory limit

Error termination. Backtrace:
#0  0x7fcf2f77fd11 in ???
#1  0x7fcf2f780859 in ???
#2  0x7fcf2f780ab4 in ???
#3  0x5639876cc1f0 in ???
#4  0x5639876e6a76 in ???
#5  0x7fcf2f442082 in __libc_start_main
    at ../csu/libc-start.c:308
#6  0x5639876c930d in ???
#7  0xffffffffffffffff in ???

Additional Context:
I compiled the code using:gfortran -o qeirreps.x qeirreps.f90 -llapack -lblas
    instead of using the Makefile.
    I noticed that ncomp = 2, but I am not using mpirun or openmp. Should i compile the code with mpifort, my system has 4 nproc and currently its difficult to install the code in HPC.

    Why is ncomp set to 2 if I'm not running in parallel? while running the file of smaller size, e. g. silicon, the ncomp in output is 1 and code runs well.
    Are there any suggestions for debugging this issue?

Thank you for your help!

**Comment by Amithigh** [comment]
The issue was resolved after reducing the number of k points, which were way high in number (1000 k points) in earlier calculations.
